version: 2

builds:
  - id: sbx
    no_unique_dist_dir: true
    main: ./cmd/sbx
    binary: sbx-{{ .Arch }}-{{ .Os }}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - binary
    name_template: "{{ .Binary }}"
    allow_different_binary_count: true

changelog:
  disable: true
